backend/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

backend/restaurant/urls.py
from django.urls import path, include

from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='restaurants_list'),
    path('manager/', views.RestaurantListManagerView.as_view(), name='restaurant_manager_list'),
    path('<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    path('manager/<int:pk>/', views.RestaurantManagerDetailView.as_view(), name='restaurant_manager_detail'),
    path('create/', views.RestaurantCreateView.as_view(), name='restaurant_create'),
    path('<int:pk>/update/', views.RestaurantUpdateView.as_view(), name='restaurant_update'),
    path('<int:pk>/delete/', views.RestaurantDeleteView.as_view(), name='restaurant_delete'),
    path('<int:restaurant_id>/tables/create/', views.RestaurantTableCreateView.as_view(), name='restaurant_table_create'),
    path('<int:pk>/tables/update/', views.RestaurantTableUpdateView.as_view(), name='restaurant_table_update'),
    path('<int:pk>/tables/delete/', views.RestaurantTableDeleteView.as_view(), name='restaurant_table_delete'),

    path('api/', include('restaurant.api.urls')),
    path('api/', include('reservation.api.urls')),
]

backend/users/urls.py
from django.urls import path, include


from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.LogIn.as_view(), name='login'),
    path('logout/', views.LoggerLogoutView.as_view(), name='logout'),
    path('api/', include('users.api.urls')),
]

backend/home/models.py
from django.db import models

# Create your models here.

backend/restaurant/models.py
from django.db import models
from django.conf import settings

class Restaurant(models.Model):
    name = models.CharField(max_length=200)
    capacity = models.IntegerField(null=True, blank=True)
    reviews = models.FloatField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    contact_email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='restaurants',
        null=True, blank=True
    )

    def __str__(self):
        return self.name
    
class Restaurant_Table(models.Model):
    table_number = models.IntegerField()
    seats = models.IntegerField()
    outdoor = models.BooleanField(default=False)
    is_smoking = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='tables')
   
     
    def __str__(self):
        return f"Table {self.table_number} at {self.restaurant.name} ({self.seats} seats) {self.is_available and 'Available' or 'Not Available'}"

backend/home/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home/base.html")

backend/home/templates/home/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}KoobFood{% endblock %}</title>
</head>
<body>
    <header>
        <h1>Bienvenue sur KoobFood</h1>
    </header>

    <nav>
        <ul>
            <li><a href="{% url 'home:home' %}">Accueil</a></li>
            <li><a href="{% url 'restaurant:restaurants_list' %}">Restaurants</a></li>
            <li><a href="{% url 'admin:index' %}">Admin</a></li>
            {% if user.is_authenticated %}
                <form action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Déconnexion</button>
                </form>
            {% else %}
                <li><a href="{% url 'users:login' %}">Se connecter</a></li>
                <li><a href="{% url 'users:signup' %}">S'inscrire</a></li>
            {% endif %}
            {% if user.is_authenticated and perms.restaurant.add_restaurant %}
                <li><a href="{% url 'restaurant:restaurant_create' %}">Ajouter un restaurant</a></li>
            {% endif %}
            {% if user.is_authenticated and perms.restaurant.view_restaurant %}
                <li><a href="{% url 'restaurant:restaurant_manager_list' %}">Mes Restaurants</a></li>
            {% endif %}
        </ul>
    </nav>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <p>&copy; 2025 KoobFood</p>
    </footer>
    
</body>
</html>