backend/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

backend/reservation/urls.py
from django.urls import path, include

from . import views

app_name = 'reservation'    
urlpatterns = [
    path('<restaurant_id>/create/', views.ReservationCreateView.as_view(), name='reservation_create'),
    path ('<restaurant_id>/<reservation_id>', views.ReservationSuccessView.as_view(), name='reservation_success'),
    path('<restaurant_id>/signup_or_login/', views.signup_or_login, name='signup_or_login'),
    path('<restaurant_id>/manager/list/', views.ReservationManagerListView.as_view(), name='reservation_manager_list'),
    path('manager/<int:pk>/', views.ReservationManagerDetailView.as_view(), name='reservation_manager_detail'),
    ]

backend/restaurant/api/urls.py
from rest_framework_nested import routers
from .views import RestaurantViewSet, RestaurantTableViewSet
from django.urls import path, include


router = routers.SimpleRouter()
router.register(r'', RestaurantViewSet, basename='api_restaurant')

restaurants_router = routers.NestedSimpleRouter(router, r'', lookup='api_restaurant')
restaurants_router.register(r'tables', RestaurantTableViewSet, basename='api_restaurant_tables')

urlpatterns = [
    path('', include(router.urls)),
    path('', include(restaurants_router.urls)),
]

backend/restaurant/urls.py
from django.urls import path, include

from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.RestaurantListView.as_view(), name='restaurants_list'),
    path('manager/', views.RestaurantListManagerView.as_view(), name='restaurant_manager_list'),
    path('<int:pk>/', views.RestaurantDetailView.as_view(), name='restaurant_detail'),
    path('manager/<int:pk>/', views.RestaurantManagerDetailView.as_view(), name='restaurant_manager_detail'),
    path('create/', views.RestaurantCreateView.as_view(), name='restaurant_create'),
    path('<int:pk>/update/', views.RestaurantUpdateView.as_view(), name='restaurant_update'),
    path('<int:pk>/delete/', views.RestaurantDeleteView.as_view(), name='restaurant_delete'),
    path('<int:restaurant_id>/tables/create/', views.RestaurantTableCreateView.as_view(), name='restaurant_table_create'),
    path('<int:pk>/tables/update/', views.RestaurantTableUpdateView.as_view(), name='restaurant_table_update'),
    path('<int:pk>/tables/delete/', views.RestaurantTableDeleteView.as_view(), name='restaurant_table_delete'),

    path('api/', include('restaurant.api.urls')),
    path('api/', include('reservation.api.urls')),
]

backend/restaurant/models.py
from django.db import models
from django.conf import settings

class Restaurant(models.Model):
    name = models.CharField(max_length=200)
    capacity = models.IntegerField(null=True, blank=True)
    reviews = models.FloatField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    contact_email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    manager = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='restaurants',
        null=True, blank=True
    )

    def __str__(self):
        return self.name
    
class Restaurant_Table(models.Model):
    table_number = models.IntegerField()
    seats = models.IntegerField()
    outdoor = models.BooleanField(default=False)
    is_smoking = models.BooleanField(default=False)
    is_available = models.BooleanField(default=True)
    restaurant = models.ForeignKey(Restaurant, on_delete=models.CASCADE, related_name='tables')
   
     
    def __str__(self):
        return f"Table {self.table_number} at {self.restaurant.name} ({self.seats} seats) {self.is_available and 'Available' or 'Not Available'}"

backend/restaurant/forms.py
from django import forms
from.models import Restaurant, Restaurant_Table

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'capacity', 'phone_number', 'contact_email', 'description', 'location']
        labels = {
            'name': 'Nom du restaurant',
            'capacity': 'Capacité',
            'phone_number': 'Numéro de téléphone',
            'contact_email': 'Adresse e-mail',
            'description': 'Description',
            'location': 'Ville',
        }
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
        }

class RestaurantTableForm(forms.ModelForm):
    class Meta:
        model = Restaurant_Table
        fields = ['table_number', 'seats', 'outdoor', 'is_smoking', 'is_available']
        labels = {
            'table_number': 'Numéro de la table',
            'seats': 'Nombre de sièges',
            'outdoor': 'Extérieur',
            'is_smoking': 'Fumeur',
            'is_available': 'Disponible',
        }

backend/restaurant/api/views.py
from rest_framework import viewsets, generics
from .serializers import RestaurantSerializer, RestaurantTableSerializer
from koobfood.api.permissions import IsManagerOrReadOnlyPermission, IsManagerPermission
from ..models import Restaurant, Restaurant_Table
from rest_framework.response import Response
from rest_framework.decorators import action

class RestaurantViewSet(viewsets.ModelViewSet):
    queryset = Restaurant.objects.all()
    serializer_class = RestaurantSerializer
    permission_classes = [IsManagerOrReadOnlyPermission]
    def perform_create(self, serializer):
        serializer.save(manager=self.request.user)
    
    @action(detail=False, methods=['get'] , permission_classes=[IsManagerPermission])
    def my_restaurants(self, request):
        user = request.user
        restaurants = Restaurant.objects.filter(manager=user)
        serializer = self.get_serializer(restaurants, many=True)
        return Response(serializer.data)

class RestaurantTableViewSet(viewsets.ModelViewSet):
    serializer_class = RestaurantTableSerializer
    permission_classes = [IsManagerPermission]

    def get_queryset(self):
        restaurant_id = self.kwargs.get('api_restaurant_pk')
        return Restaurant_Table.objects.filter(
            restaurant_id=restaurant_id,
            restaurant__manager=self.request.user
        )
    def perform_create(self, serializer):
        restaurant_id = self.kwargs.get('api_restaurant_pk')
        restaurant = Restaurant.objects.get(id=restaurant_id)
        serializer.save(restaurant=restaurant)

backend/restaurant/views.py
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views import generic
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.core.exceptions import PermissionDenied

from .models import Restaurant, Restaurant_Table
from .forms import RestaurantForm, RestaurantTableForm

# ------------------------RESTAURANT MANAGER--------------------------------

class RestaurantManagerMixin(LoginRequiredMixin, PermissionRequiredMixin):
    model = Restaurant

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(manager=self.request.user)
    
class RestaurantListManagerView(RestaurantManagerMixin, generic.ListView):
    template_name = 'restaurant/restaurant_manager_list.html'
    context_object_name = 'restaurant_list'
    permission_required = 'restaurant.view_restaurant'

class RestaurantManagerDetailView(RestaurantManagerMixin, generic.DetailView):
    template_name = 'restaurant/restaurant_manager_detail.html'
    context_object_name = 'restaurant_detail'
    permission_required = 'restaurant.view_restaurant'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['restaurant_tables'] = self.object.tables.all()
        return context
    
class RestaurantCreateView( RestaurantManagerMixin, generic.CreateView):
    form_class = RestaurantForm
    template_name = 'restaurant/restaurant_create.html'
    permission_required = 'restaurant.add_restaurant'

    def form_valid(self, form):
        form.instance.manager = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('restaurant:restaurant_table_create', kwargs={'restaurant_id': self.object.pk})
    
class RestaurantUpdateView( RestaurantManagerMixin,generic.UpdateView):
    form_class = RestaurantForm
    template_name = 'restaurant/restaurant_update.html'
    permission_required = 'restaurant.change_restaurant'

    def get_success_url(self):
        return reverse_lazy('restaurant:restaurant_manager_detail', kwargs={'pk': self.object.pk})
    
class RestaurantDeleteView(RestaurantManagerMixin, generic.DeleteView):
    template_name = 'restaurant/restaurant_delete.html'
    success_url = reverse_lazy('restaurant:restaurant_manager_list')
    permission_required = 'restaurant.delete_restaurant'


# ------------------------RESTAURANTS CUSTOMER--------------------------------

class RestaurantListView(generic.ListView):
    model = Restaurant
    template_name = 'restaurant/restaurant_list.html'
    context_object_name = 'restaurant_list'
    paginate_by = 5

    def get_queryset(self):
        return Restaurant.objects.all().order_by('id')
    
class RestaurantDetailView(generic.DetailView):
    model = Restaurant
    template_name = 'restaurant/restaurant_detail.html'
    context_object_name = 'restaurant_detail'

# ------------------------TABLES DU RESTAURANT--------------------------------

class RestaurantTableCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Restaurant_Table
    form_class = RestaurantTableForm
    template_name = 'restaurant_table/restaurant_table_create.html'
    success_url = reverse_lazy('restaurant:restaurant_manager_list')
    permission_required = 'restaurant.add_restaurant_table'

    def form_valid(self, form): 
        restaurant = Restaurant.objects.get(pk=self.kwargs['restaurant_id']) 
        if restaurant.manager != self.request.user: 
            return HttpResponseForbidden("Vous n'êtes pas autorisé à ajouter des tables à ce restaurant.") 
        form.instance.restaurant = restaurant 
        response = super().form_valid(form)

        if self.request.POST.get('action') == 'save':
            return redirect('restaurant:restaurant_table_create', restaurant_id=restaurant.pk)
        return response
    
class RestaurantTableUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Restaurant_Table
    form_class = RestaurantTableForm
    template_name = 'restaurant_table/restaurant_table_update.html'
    permission_required = 'restaurant.change_restaurant_table'

    def get_success_url(self):
        return reverse_lazy('restaurant:restaurant_manager_detail', kwargs={'pk': self.object.restaurant.pk})

    def get_queryset(self):
        return Restaurant_Table.objects.filter(restaurant__manager=self.request.user)
    
class RestaurantTableDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    model = Restaurant_Table
    template_name = 'restaurant_table/restaurant_table_delete.html'
    success_url = reverse_lazy('restaurant:restaurant_list')
    permission_required = 'restaurant.delete_restaurant_table'

    def get_success_url(self):
        return reverse_lazy('restaurant:restaurant_manager_detail', kwargs={'pk': self.object.restaurant.pk})

    def get_queryset(self):
        return Restaurant_Table.objects.filter(restaurant__manager=self.request.user)
    
# ------------------------API VIEWS--------------------------------
        


        
    
         

backend/restaurant/templates/restaurant/restaurant_create.html
{%extends "home/base.html" %}

{% block title %}Créer un restaurant{% endblock %}

{% block content %}
<h2>Créer un nouveau restaurant</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Suivant</button>    
</form>
{% endblock %}

backend/restaurant/templates/restaurant/restaurant_delete.html
{% extends "home/base.html" %}

{% block title %}Supprimer le restaurant{% endblock %}

{% block content %}
<h2>Supprimer le restaurant</h2>
<p>Êtes-vous sûr de vouloir supprimer le restaurant "{{ object.name }}" ? Cette action est irréversible.</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirmer la suppression</button>
</form>
<a href="{% url 'restaurant:restaurant_manager_detail' object.pk %}">Annuler</a>
{% endblock %}

backend/restaurant/templates/restaurant/restaurant_detail.html
{%extends "home/base.html" %}

{% block title %}Détail des restaurants{% endblock %}

{% block content %}
<h2>{{restaurant_detail.name}}</h2>
<p>{{restaurant_detail.description}}</p>
<p>Lieu: {{restaurant_detail.location}}</p> 
<p> Note : {{restaurant_detail.reviews}}/5</p>
<p>Numéro de téléphone : {{restaurant_detail.phone_number}}</p>
    <a href="{% url 'reservation:reservation_create' restaurant_detail.id %}">
        <strong>Réserver une table</strong>
    </a><br>

{% endblock %}

backend/restaurant/templates/restaurant/restaurant_list.html
{% extends "home/base.html" %}

{% block title %}Liste des Restaurants{% endblock %}

{% block content %}
<h2>Liste des Restaurants</h2>
<ul>
    {% for restaurant in restaurant_list %}
        <li><a href="{% url 'restaurant:restaurant_detail' restaurant.pk %}" >{{ restaurant.name }} - {{ restaurant.location }}<a></li>
    {% empty %}
        <li>Aucun restaurant trouvé.</li>
    {% endfor %}    
</ul>   

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

backend/restaurant/templates/restaurant/restaurant_manager_detail.html
{%extends "home/base.html" %}

{% block title %}Détail des restaurants{% endblock %}

{% block content %}
<h2>{{restaurant_detail.name}}</h2>
<p>{{restaurant_detail.description}}</p>
<p>Lieu: {{restaurant_detail.location}}</p> 
<p> Note : {{restaurant_detail.reviews}}/5</p>
<p>Numéro de téléphone : {{restaurant_detail.phone_number}}</p>

<a href="{% url 'restaurant:restaurant_update' restaurant_detail.pk %}">Modifier le restaurant</a>
<a href="{% url 'restaurant:restaurant_delete' restaurant_detail.pk %}">Supprimer le restaurant</a><br>
<a href="{% url 'restaurant:restaurant_table_create' restaurant_detail.pk %}">Ajouter une table</a>

<h3>Tables disponibles</h3>
    <ul>    
        {% for table in restaurant_tables %}
            <li>
                Table n°{{ table.table_number }} - Capacité: {{ table.seats }} personnes - 
                {% if table.is_available %}Disponible{% else %}Non disponible{% endif %}
                
                    <a href="{% url 'restaurant:restaurant_table_update' table.pk %}">Modifier</a>

                    <a href="{% url 'restaurant:restaurant_table_delete' table.pk %}">Supprimer</a>
            </li>
        {% empty %}
            <li>Aucune table disponible.</li>
        {% endfor %}
    </ul>

{% endblock %}

backend/restaurant/templates/restaurant/restaurant_manager_list.html
{%extends "home/base.html" %}

{% block title %}Gestion des Restaurants{% endblock %}

{% block content %}
<h2>Mes Restaurants</h2>
<ul>
    {% for restaurant in restaurant_list %}
        <li><a href="{% url 'restaurant:restaurant_manager_detail' restaurant.pk %}" >{{ restaurant.name }} - {{ restaurant.location }}<a>
            <a href="{% url 'reservation:reservation_manager_list' restaurant.pk %}">Voir les réservations</a>    
        </li>
    {% empty %}
        <li>Aucun restaurant trouvé.</li>
    {% endfor %}
</ul>
{% endblock %}

backend/restaurant/templates/restaurant/restaurant_update.html
{% extends "home/base.html" %}

{% block title %}Mettre à jour le restaurant{% endblock %}

{% block content %} 
<h2>Mise à jour du restaurant</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enregistrer</button>    
</form>

<a href="{% url 'restaurant:restaurant_manager_detail' form.instance.pk %}">Annuler</a>

{% endblock %}