backend/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

backend/reservation/api/urls.py
from django.urls import path, include
from rest_framework_nested import routers
from .views import ReservationViewSet
from restaurant.api.views import RestaurantViewSet

router = routers.SimpleRouter()
router.register(r'', RestaurantViewSet, basename='restaurant')

reservation_router = routers.NestedSimpleRouter(router, r'', lookup='restaurant')
reservation_router.register(r'reservation', ReservationViewSet, basename='api_reservation')

urlpatterns = [
    path('', include(router.urls)),
    path('', include(reservation_router.urls)),
]

backend/reservation/urls.py
from django.urls import path, include

from . import views

app_name = 'reservation'    
urlpatterns = [
    path('<restaurant_id>/create/', views.ReservationCreateView.as_view(), name='reservation_create'),
    path ('<restaurant_id>/<reservation_id>', views.ReservationSuccessView.as_view(), name='reservation_success'),
    path('<restaurant_id>/signup_or_login/', views.signup_or_login, name='signup_or_login'),
    path('<restaurant_id>/manager/list/', views.ReservationManagerListView.as_view(), name='reservation_manager_list'),
    path('manager/<int:pk>/', views.ReservationManagerDetailView.as_view(), name='reservation_manager_detail'),
    ]

backend/users/urls.py
from django.urls import path, include


from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', views.LogIn.as_view(), name='login'),
    path('logout/', views.LoggerLogoutView.as_view(), name='logout'),
    path('api/', include('users.api.urls')),
]

backend/reservation/models.py
from django.db import models

class Reservation(models.Model):
    reservation_date = models.DateTimeField()
    number_of_people = models.PositiveIntegerField()
    customer_message = models.TextField(blank=True, null=True)
    restaurant = models.ForeignKey('restaurant.Restaurant', on_delete=models.CASCADE)
    customuser = models.ForeignKey('users.CustomUser', null=True, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        from .tasks import send_mail_after_reservation_manager, send_mail_after_reservation_customer
        send_mail_after_reservation_manager.delay(self.id)
        send_mail_after_reservation_customer.delay(self.id)


    def __str__(self):
        return f"Reservation pour {self.number_of_people} personnes à {self.restaurant.name} le {self.reservation_date.strftime('%Y-%m-%d %H:%M')}"
    
class Reservation_Table(models.Model):
    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    restaurant_table = models.ForeignKey('restaurant.Restaurant_Table', on_delete=models.CASCADE)

    def __str__(self):
        return f" {self.reservation.reservation_date.strftime('%Y-%m-%d %H:%M')} : Table n°{self.restaurant_table.table_number} - {self.reservation.number_of_people} personnes"
    

backend/reservation/forms.py
from django import forms
from django.utils import timezone
from .models import Reservation, Reservation_Table
from restaurant.models import Restaurant_Table


class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ["reservation_date", "number_of_people", "customer_message"]
        labels = {
            "reservation_date": "Date et heure de la réservation",
            "number_of_people": "Nombre de personnes",
            "customer_message": "Message du client (optionnel)",
        }
        widgets = {
            "reservation_date": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user", None)
        self.restaurant_id = kwargs.pop("restaurant_id", None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()

        number = cleaned_data.get("number_of_people")
        if number and number <= 0:
            self.add_error("number_of_people", "Le nombre de personnes doit être supérieur à zéro.")

        return cleaned_data

    def clean_reservation_date(self):
        date = self.cleaned_data.get("reservation_date")
        if date and date <= timezone.now():
            raise forms.ValidationError("La date doit être dans le futur.")
        return date

    def clean_number_of_people(self):
        number = self.cleaned_data.get("number_of_people")
        if number and self.restaurant_id:
            table = Restaurant_Table.objects.filter(
                restaurant_id=self.restaurant_id,
                seats__gte=number,
                is_available=True
            ).order_by("seats").first()

            if not table:
                raise forms.ValidationError("Aucune table disponible pour ce nombre de personnes.")
        if number <= 0:
            raise forms.ValidationError("Le nombre de personnes doit être supérieur à zéro.")
        return number

    def save(self, commit=True):
        reservation = super().save(commit=False)
        reservation.restaurant_id = self.restaurant_id
        reservation.customuser = self.user

        if commit:
            reservation.save()

            table = Restaurant_Table.objects.filter(
                restaurant_id=self.restaurant_id,
                seats__gte=self.cleaned_data["number_of_people"],
                is_available=True
            ).order_by("seats").first()

            if table:
                Reservation_Table.objects.create(reservation=reservation, restaurant_table=table)
                table.is_available = False
                table.save()

        return reservation

backend/reservation/api/views.py
from .serializers import ReservationSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework import viewsets
from koobfood.api.permissions import IsOwnerOrManagerReadOnlyPermission
from ..models import Reservation
from restaurant.models import Restaurant
from rest_framework.response import Response

class ReservationViewSet(viewsets.ModelViewSet):
    queryset = Reservation.objects.all()
    serializer_class = ReservationSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrManagerReadOnlyPermission]

    def get_queryset(self):
        user = self.request.user
        if user.groups.filter(name='Manager').exists():
            return Reservation.objects.filter(restaurant__manager=user)
        return Reservation.objects.filter(customuser=user)
    
    def perform_create(self, serializer):
        restaurant_id=self.kwargs.get('restaurant_pk')
        serializer.save(customuser=self.request.user, restaurant_id=restaurant_id)

backend/reservation/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic
from .models import Reservation, Reservation_Table
from .forms import ReservationForm
from restaurant.models import Restaurant
from users.models import CustomUser
from restaurant.models import Restaurant_Table
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

import logging

logger = logging.getLogger(__name__)

# -----------------------RESERVATIONS CUSTOMER--------------------------------

def signup_or_login(request, restaurant_id):
    next_url = request.GET.get('next')
    return render(request, 'reservation/signup_or_login.html', {'next': next_url, 'restaurant_id': restaurant_id})

class ReservationCreateView(LoginRequiredMixin, generic.CreateView):
    model = Reservation
    template_name = 'reservation/reservation_form.html'
    form_class = ReservationForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["restaurant_id"] = self.kwargs["restaurant_id"]
        kwargs["user"] = self.request.user
        return kwargs

    def get_success_url(self):
        return reverse('reservation:reservation_success', kwargs={
            'restaurant_id': self.kwargs['restaurant_id'],
            'reservation_id': self.object.pk
        })
    
    def form_valid(self, form):
        logger.info(f"Nouvelle réservation créée par {self.request.user.username} pour le restaurant ID {self.kwargs['restaurant_id']} le {form.cleaned_data['reservation_date']}.")
        return super().form_valid(form)


class ReservationSuccessView(generic.DetailView):
    model = Reservation
    template_name = 'reservation/reservation_success.html'
    context_object_name = 'reservation'

    def get_object(self):
        return Reservation.objects.get(pk=self.kwargs['reservation_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['restaurant'] = Restaurant.objects.get(pk=self.kwargs['restaurant_id'])
        return context


# -----------------------RESERVATIONS MANAGER --------------------------------
class ReservationManagerMixin(LoginRequiredMixin):
    model = Reservation_Table

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(reservation__restaurant__manager=self.request.user)
    
class ReservationManagerListView(ReservationManagerMixin, generic.ListView):
    template_name = 'reservation/reservation_manager_list.html'
    context_object_name = 'reservation_list'

    def get_queryset(self):
      queryset = super().get_queryset()
      return queryset.filter(reservation__restaurant=self.kwargs['restaurant_id'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        now = timezone.now()
        context['upcoming_reservations'] = self.get_queryset().filter(reservation__reservation_date__gte=now).order_by('reservation__reservation_date')
        context['past_reservations'] = self.get_queryset().filter(reservation__reservation_date__lt=now).order_by('reservation__reservation_date')
        context['today_reservations'] = self.get_queryset().filter(reservation__reservation_date__date=now.date()).order_by('reservation__reservation_date')
        return context
    
class ReservationManagerDetailView(ReservationManagerMixin, generic.DetailView):
    template_name = 'reservation/reservation_manager_detail.html'
    context_object_name = 'reservation'

backend/reservation/templates/reservation/reservation_form.html
{% extends "home/base.html" %}

{% block title %}Reservation restaurant{% endblock %}

{% block content %}
<h2>Reservation pour le restaurant {{ restaurant.name }} </h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Valider</button>
</form>
{% endblock %}

backend/reservation/templates/reservation/reservation_manager_detail.html
{% extends "home/base.html" %}

{% block title %}Détail de la réservation{% endblock %}

{% block content %}
<h2>Détail de la réservation</h2>
<p><strong>Restaurant :</strong> {{ reservation.reservation.restaurant.name }}</p>
<p><strong>Date et heure :</strong> {{ reservation.reservation.reservation_date|date:"d/m/Y H:i" }}</p>
<p><strong>Nombre de personnes :</strong> {{ reservation.reservation.number_of_people }}</p>
<p><strong>Table assignée :</strong> {{ reservation.restaurant_table.table_number }}</p>
{% if reservation.reservation.customer_message %}
    <p><strong>Message du client :</strong> {{ reservation.reservation.customer_message }}</p>
{% endif %}

<h2>Informations sur le client</h2>
<p><strong>Nom :</strong> {{ reservation.reservation.customuser.first_name }}</p>
<p><strong>Prénom :</strong> {{ reservation.reservation.customuser.last_name }}</p>
<p><strong>Email :</strong> {{ reservation.reservation.customuser.email }}</p>
<p><strong>Téléphone :</strong> {{ reservation.reservation.customuser.phone_number }}</p>

<a href="{% url 'reservation:reservation_manager_list' reservation.reservation.restaurant.pk %}">Retour à la liste des réservations</a>
{% endblock %}

backend/reservation/templates/reservation/reservation_manager_list.html
{% extends "home/base.html" %}

{% block title %}Liste des Réservations{% endblock %}

{% block content %}
<h2>Liste des réservations pour {{restaurant.name}}</h2>

<h3>Aujourd'hui ({{ today_reservations.count }})</h3>
<ul>
    {% for reservation in today_reservations %}
        <li>
            {{ reservation }}
            {% if reservation.customer_message %}
                Message du client : {{ reservation.customer_message }}
            {% endif %}
            <a href="{% url 'reservation:reservation_manager_detail' reservation.pk %}">Détails</a>
        </li>
    {% empty %}
        <li>Aucune réservation aujourd'hui.</li>
    {% endfor %}
</ul>


<h3>À venir</h3>
<ul>
    {% for reservation in upcoming_reservations %}
        <li>
             {{ reservation }}
            {% if reservation.customer_message %}
                Message du client : {{ reservation.customer_message }}
            {% endif %}
            <a href="{% url 'reservation:reservation_manager_detail' reservation.pk %}">Détails</a>
        </li>
    {% empty %}
        <li>Aucune réservation à venir.</li>
    {% endfor %}
</ul>


<h3>Passées</h3>
<ul>
    {% for reservation in past_reservations %}
        <li>
             {{ reservation }}
            <a href="{% url 'reservation:reservation_manager_detail' reservation.pk %}">Détails</a>
        </li>
    {% empty %}
        <li>Aucune réservation passée.</li>
    {% endfor %}
</ul>
{% endblock %}

backend/reservation/templates/reservation/reservation_success.html
{% extends "home/base.html" %}
{% block title %}Réservation réussie{% endblock %}

{% block content %}
<p>Merci {{ user.username }} pour votre réservation dans le restaurant {{ restaurant.name }} pour {{ reservation.number_of_people }} personne(s) !</p>
<p>Date et heure : {{ reservation.reservation_date }}h</p>
<strong>A très vite !</strong>
{% endblock %}

backend/reservation/templates/reservation/signup_or_login.html
{% extends "home/base.html" %}

{% block title %}Connexion ou Inscription{% endblock %}

{% block content %}

<h2>Veuillez vous connecter ou vous inscrire pour continuer</h2>
<a href="{% url 'users:login' %}?next={{ next }}">Se connecter</a>
<a href="{% url 'users:signup' %}?next={{ next }}">S'inscrire</a>

{% endblock %}